### ISSUE TITLE
How to use NuShellX in linux?

### ISSUE THREAD

**Issue by Hachiman512** [hamad12a/NuShellX#1]
As I mentioned in the title, is it possible to use nushellx in Linux? If yes, then can you help me with how I can use it?

**Comment by hamad12a** [comment]
Hi, 

To run this code on Linux you need Wine installed correctly on your machine. 

![image](https://github.com/hamad12a/NuShellX/assets/54325150/8faff897-7f60-4d01-b998-3e7366393552)


After that, you open your Terminal within the extracted directory of NuShellX, change your current working directory to `build` directory of the code with `cd /where/you/extracted/NuShellX/`, 

![image](https://github.com/hamad12a/NuShellX/assets/54325150/96601859-88ba-4fa3-b4ba-568cdd168bd2)

then issue:

![image](https://github.com/hamad12a/NuShellX/assets/54325150/04a736e0-b953-4b7b-a5ff-90c041737343)

As you can see the commands are running as expected

![image](https://github.com/hamad12a/NuShellX/assets/54325150/95472c76-4dd6-4aff-b58e-21c54310e85c)

However, you need to consult the manual provided within the code (the pdf file) for technical implementation.

**Comment by Hachiman512** [comment]
Thanks for your response. I followed this procedure but It's not running because of my processor.

FYI I have AMD processor.
![Screenshot from 2024-06-15 07-14-13](https://github.com/hamad12a/NuShellX/assets/128797803/205895ff-0658-4da3-90dd-153f2881cc9e)

**Comment by hamad12a** [comment]
you have to compile it from source
